### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by sinnbeck** [highcharts/crossing-specific-value#2]
Have this plugin stopped working?
http://jsfiddle.net/jsCJF/124/
It does not seem to do anything (it is the same on the highcharts plugins page)
http://www.highcharts.com/plugin-registry/single/6/Crossing-Specific-Values

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! The plugin is working, but the script source was outdated. Should be https://rawgithub.com/highcharts/crossing-specific-value/master/crossing-specific-value.js. For production, please download to your own server.
